### ISSUE TITLE
The plural of Pokémon is also Pokémon

### ISSUE THREAD

**Issue by Wmaarts** [nicojs/lit-xml#13]
https://googlethatforyou.com?q=what%20is%20the%20plural%20of%20pokemon

It's incorrect in the README. `Pokemons` is not a word.
![image](https://user-images.githubusercontent.com/5868064/100448677-f81e9d80-30b2-11eb-96cd-fac3332efb75.png)

😁🤓

**Comment by hugo-vrijswijk** [comment]
What would your suggestion for the element be that contains a list of Pokemon?

**Comment by Wmaarts** [comment]
I'd say `<Pokedex>` makes the most sense.
